"""empty message

Revision ID: 5bfdc718e856
Revises: 
Create Date: 2021-09-11 21:49:45.777846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfdc718e856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buoy_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buoy_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('wdir', sa.Integer(), nullable=True),
    sa.Column('wspd', sa.Float(), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('wvht', sa.Float(), nullable=True),
    sa.Column('dpd', sa.Integer(), nullable=True),
    sa.Column('apd', sa.Float(), nullable=True),
    sa.Column('mwd', sa.Integer(), nullable=True),
    sa.Column('pres', sa.Float(), nullable=True),
    sa.Column('atmp', sa.Float(), nullable=True),
    sa.Column('wtmp', sa.Float(), nullable=True),
    sa.Column('dewp', sa.String(), nullable=True),
    sa.Column('vis', sa.String(), nullable=True),
    sa.Column('ptdy', sa.String(), nullable=True),
    sa.Column('tide', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'date'),
    sa.UniqueConstraint('id')
    )
    op.create_table('noaa_hourly_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('buoy_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('windspeed', sa.Integer(), nullable=True),
    sa.Column('winddir', sa.String(), nullable=True),
    sa.Column('forecast', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('buoy_id', 'starttime'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tide_vals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buoy_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('datetime', sa.Date(), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=False),
    sa.Column('highlow', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tide_vals')
    op.drop_table('noaa_hourly_forecast')
    op.drop_table('buoy_data')
    # ### end Alembic commands ###
