"""empty message

Revision ID: f8b3e9fec561
Revises: 5bfdc718e856
Create Date: 2021-09-11 22:12:02.872368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b3e9fec561'
down_revision = '5bfdc718e856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noaa_hourly_forecast', sa.Column('buoyid', sa.Integer(), nullable=False))
    op.drop_column('noaa_hourly_forecast', 'buoy_id')
    op.create_unique_constraint(None, 'tide_vals', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tide_vals', type_='unique')
    op.add_column('noaa_hourly_forecast', sa.Column('buoy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('noaa_hourly_forecast', 'buoyid')
    # ### end Alembic commands ###
